### PR TITLE
Updates for Swift 2 and Methods

### PR DESCRIPTION
**Pull request by narendasan**
I added some updates for support of swift 2 and methods (on OSX 10.11), the compiled version of the code is the new one, may want to check it.

### CODE REVIEW

**Comment by Tedko** [comment]
Yeah just tried it, but Swift 2.0 is not working on 10.10; how about keep 2 ver of Swift?

**Comment by tengyifei** [comment]
See 9a8ec8bae4bc15906eb2c3764e2e0bc7c0251f96. We had the Swift 2.0 version initially, but it wouldn't work on OS X 10.10. Bad news.

**Comment by tengyifei** [comment]
We appreciate your contribution very much, but sadly this could not be merged.

**Comment by narendasan** [comment]
Just FYI Xcode7 is in GM so swift 2 will be rolled out really soon. I would recommend a version detecting statement which selects the binary to run and just have one for 1.2 and another for 2.0

On September 11, 2015 at 10:48:12 AM, Teng Yifei (notifications@github.com) wrote:

We appreciate your contribution very much, but sadly this could not be merged.

**Comment by Tedko** [comment]
Now using swift let us face some problem about compatibility. Keeping updt it will take a lot of effort. 
checkout Golang branch. We try to use go lang.

**Pull request closed without merging**
